name: Nightly Docker build

on:
  schedule:
    - cron:  '30 1 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Store build timestamp
        run: echo "BUILD_DATE=$(date +'%F')" >> $GITHUB_ENV    
      - name: Confirm git commit SHA and timestamp output
        run: echo "Short commit SHA ${{ env.COMMIT_SHORT_SHA }}, build date ${{ env.BUILD_DATE }}"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            forinil/virt-manager:nightly-latest
            forinil/virt-manager:nightly-${{ env.COMMIT_SHORT_SHA }}-${{ env.BUILD_DATE }}
            ghcr.io/forinil/virt-manager:nightly-latest
            ghcr.io/forinil/virt-manager:nightly-${{ env.COMMIT_SHORT_SHA }}-${{ env.BUILD_DATE }}
